version: '3'
services:
  reposado:
    image: "macadmins/reposado"
    ports:
      - "443:443"
    volumes:
      - reposado:/reposado

  margarita:
    image: "margarita"
    ports:
     - "80:80"
    volumes:
      - reposado:/reposado
    # - /path/to/your/saml/:/app/saml
    # (Optional)
    # - /path/to/your/reposado/metadata/:/reposado/metadata/
    # - /path/to/your/reposado/html/:/reposado/html/
    depends_on:
      - reposado

volumes:
  reposado:
